# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  project_repos:
    saps-dashboard:
      repo: 'https://github.com/EOSC-synergy/saps-dashboard/'
      branch: master

sqa_criteria:
   qc_doc:
     repos:
       saps-dashboard:
         container: dashboard-docs
         commands:
           #- pip install recommonmark
           - make html -C /saps-dashboard-repo/docs/
