config:
  credentials: []
  project_repos: {}
environment: {}
sqa_criteria:
  qc_style:
    repos:
      this_repo:
        commands:
        - hadolint docker/Dockerfile
        container: hadolint
timeout: 600
