config:
  project_repos:
    saps-dashboard:
      repo: 'https://github.com/EOSC-synergy/saps-dashboard/'
      branch: master
      dockerhub: ufcgsaps/dashboard
      dockertag: latest

sqa_criteria:
  qc_style:
    repos:
      saps-dashboard:
        container: processing
        tox:
          testenv:
            - stylecheck
